# Logistic Regression

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from google.colab import drive
import seaborn as sbn

In [ ]:
drive.mount("/gdrive")
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [ ]:
!ls "MyDrive/Machine Learning"

 Classification.ipynb	 Odev.ipynb
 MachineLearning.ipynb	'Polinom Regression.ipynb'
 missingvalues.ipynb	'SVM&KERNEL&NAİLBAYES .ipynb'
 MultipleEX.ipynb	 veri


In [ ]:
veriler = pd.read_csv("MyDrive/Machine Learning/veri/veriler.csv")

In [ ]:
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [ ]:
x = veriler.iloc[:,1:4].values
y =  veriler.iloc[:,-1:].values

In [ ]:
x

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]])

In [ ]:
print(y.shape)
print(x.shape)

(22, 1)
(22, 3)


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(x_train)

In [ ]:
X_test = sc.transform(x_test)

In [ ]:
print(X_test)
print("\n")
print(X_train)

[[-0.10726058 -0.05470872  0.6225517 ]
 [-0.06435635 -0.49813728  0.17787191]
 [ 0.02145212 -0.21595547  2.66807872]
 [-0.19306904 -0.33689053  1.42297532]
 [-1.78052563 -1.26405934 -1.2451034 ]
 [-0.02145212 -0.45782559  1.51191128]
 [-0.49339867 -0.69969571  1.68978319]
 [-0.32178174 -1.10281259  0.35574383]]


[[ 0.45049444 -0.29657884 -0.26680787]
 [ 1.00824945  0.5096549   0.        ]
 [ 1.13696215  0.91277178 -0.17787191]
 [-1.6089087  -1.18343596 -1.15616745]
 [-1.35148331 -1.34468271 -1.33403936]
 [ 0.57920713  0.91277178  0.44467979]
 [ 0.87953676  0.5096549   0.17787191]
 [ 0.79372829  1.51744708  0.71148766]
 [ 0.36468597  0.91277178  0.88935957]
 [ 0.70791983  0.8321484   0.26680787]
 [-1.43729177 -1.50592946 -1.42297532]
 [-1.56600447 -1.50592946 -1.33403936]
 [ 0.32178174  0.10653803  1.95659106]
 [-0.27887751 -0.37720222  1.2451034 ]]


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logr = LogisticRegression(random_state=0)

In [ ]:
logr.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = logr.predict(X_test)

In [ ]:
print(y_pred)
print(y_test)

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


# Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(y_test,y_pred)

In [ ]:
cm

array([[0, 1],
       [7, 0]])

# K-NN


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn_Reg = KNeighborsClassifier(n_neighbors=5, metric="minkowski")

In [ ]:
knn_Reg.fit(X_train,y_train)
y_pred_knn = knn_Reg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


In [ ]:
cm_knn = confusion_matrix(y_test,y_pred)

In [ ]:
cm_knn

array([[0, 1],
       [7, 0]])

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc = SVC(kernel="poly")

In [ ]:
svc.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svc.predict(X_test)

In [ ]:
cm_svr = confusion_matrix(y_test,y_pred)

In [ ]:
cm_svr

array([[1, 0],
       [7, 0]])

# Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
gnb = GaussianNB()

In [ ]:
gnb.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = gnb.predict(X_test)

In [ ]:
cm_gnb = confusion_matrix(y_test,y_pred)

In [ ]:
cm_gnb

array([[0, 1],
       [6, 1]])

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
multi = MultinomialNB()

In [ ]:
multi.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred = multi.predict(X_test)

In [ ]:
cm_mult = confusion_matrix(y_test,y_pred)

In [ ]:
cm_mult

array([[1, 0],
       [7, 0]])

# Decision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dtc = DecisionTreeClassifier(criterion="entropy")

In [ ]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred= dtc.predict(X_test)

In [ ]:
cm = confusion_matrix(y_test,y_pred)

In [ ]:
cm


array([[1, 0],
       [1, 6]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier(n_estimators=10, criterion="entropy")

In [ ]:
rfc.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred = rfc.predict(X_test)

In [ ]:
y_pred

array(['e', 'k', 'k', 'k', 'e', 'k', 'k', 'e'], dtype=object)

In [ ]:
y_test

array([['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [ ]:
cm = confusion_matrix(y_test,y_pred)

In [ ]:
cm

array([[1, 0],
       [2, 5]])